[tool.poetry]
name = "spaceship-titanic"
version = "0.1.0"
description = "Solving the Spaceship Titanic Kaggle Competition"
authors = ["Javier Vela <javier.vela00@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
